# Generated by Django 5.1.7 on 2025-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_add_equipment_add_member_add_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='add_plan',
            name='duration',
            field=models.CharField(choices=[('Yearly Plans', 'Yearly Plans'), ('Monthly Plans', 'Monthly Plans')], max_length=50),
        ),
    ]
